### ISSUE TITLE
运行工程时，选择DX渲染，报以下错误：SharpDX.SharpDXException

### ISSUE THREAD

**Issue by aaronduhu** [qian-o/MediaWPF#3]
运行工程时，选择DX渲染，报以下错误，环境：VS2022 ，win11
SharpDX.SharpDXException:“HRESULT: [0x8876021C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_WASSTILLDRAWING/WasStillDrawing], Message: Unknown”

**Comment by qian-o** [comment]
方便提供下处理器型号吗？

**Comment by qian-o** [comment]
我在r7 5800h的核显上复现过这个问题，但一直没找到原因。
可以尝试首选英伟达显卡
![image](https://user-images.githubusercontent.com/84434846/200800382-a7e0587d-daff-42fc-b9a3-202747485dfe.png)
或者将LockFlags改为NoDirtyUpdate
![image](https://user-images.githubusercontent.com/84434846/200800448-42f9ee0f-f8dc-42a3-8a1c-74efdc7e6e21.png)

**Comment by aaronduhu** [comment]
首先非常感谢您的回复，我原本只是试一试的心态提问，没有注意信息，对此我十分抱歉。
以下是我修改设置后的相关信息，不会异常奔溃了，但是会花屏
![image](https://user-images.githubusercontent.com/5250901/201027149-57332a95-394a-4bae-bc69-bd68df09d643.png)
![image](https://user-images.githubusercontent.com/5250901/201027205-3482327c-f9c2-43d8-880e-87b45d20a153.png)
![image](https://user-images.githubusercontent.com/5250901/201027030-4a02d06b-adb9-4422-9c83-02c9b64f9c29.png)

**Comment by aaronduhu** [comment]
还原刚才的设置，只把LockFlags改为NoDirtyUpdate，就正常了，非常感谢您的答复。

**Comment by aaronduhu** [comment]
![image](https://user-images.githubusercontent.com/5250901/201028423-afeadc4c-a44f-408b-9667-3c8f4d9b964c.png)

**Comment by qian-o** [comment]
ok，问题解决了就行
