### ISSUE TITLE
下载测试，并不是很可用。

### ISSUE THREAD

**Issue by LazyCuteLion** [qian-o/MediaWPF#4]
测试了8K视频（7680x4320@60-vp9，非hdr视频），几种方案都播放不起来。
测试4K视频（大熊兔3840x2160@60-h.264，非hdr视频），最流畅的反而是MediaElement方案。
OpenGL、DirectX均会报错（Memcpy方法），且性能不佳（调用集显没有调用独显，CPU、内存占用高）
错误信息：Attempted to read or write protected memory. This is often an indication that other memory is corrupt

**Comment by qian-o** [comment]
在这个项目中，使用了libvlc来处理视频帧回调，但由于长时间未维护，存在多次内存拷贝以及无法混合字幕的问题。
如果您有更优秀的解决方案，欢迎您提出建议。
